[package]
name = "mudfish"
version = "0.1.0"
edition = "2021"

[dependencies]
adblock = "0.8.11"
clap = { version = "4.5.9", features = ["derive", "env"] }
rmp-serde = "1.3.0"
selectors = "0.25.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
swc = "0.282.1"
